---
title: "Extracting data for bozen"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{example_bozen}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

- read the necessary libraries


```{r setup, echo=T, message=FALSE, warning=FALSE}
library(rainfallR)
library(here)
library(sf)
library(dplyr)
library(tmap)
library(mapview)
library(tidyverse)
library(raster)
library(leaflet)
```

- first we need to set some paths

```{r}
# the path to the directory of the NetCDFs which are stored for each month
path_ncdf = "\\\\projectdata.eurac.edu/projects/Proslide/PREC_GRIDS/"

# then we need a path to a spatial object (shape, geopackage...)
path_spatial = here(... = "../../../Desktop/bolzano.gpkg")
spatial.obj = read_sf(path_spatial)
head(spatial.obj)
```

- check to see if we are in the right location

```{r, echo=F}
data(World)
tmap_mode("view")
tm_shape(spatial.obj) +
tm_dots()
```


- set some more options

```{r, echo=T}
dts = c(as.Date("2016-01-12"), as.Date("2016-01-14"))
seqq = T
days_back = 4
```

- and get the data

```{r getdata, echo=T, warning=F, message=F}
res = get_rainfall(data_path = path_ncdf,
                   spatial.obj = spatial.obj,
                   dts = dts,
                   seqq = seqq, 
                   days_back = days_back)

lapply(res, head)
```

```{r plot, echo=F}
# get the dates back for the first date
dates_back = names(res[[1]]) %>% as.Date(., "%Y%m%d") %>% na.omit()

# put it in long format
geom = res[[1]] %>% dplyr::select(geometry)
df_new = res[[1]] %>% 
  st_drop_geometry() %>% 
  pivot_longer(cols = everything(), names_to="dates", values_to="precip")

df_new$x = st_coordinates(geom)[[1]]
df_new$y = st_coordinates(geom)[[2]]

df_sf = st_as_sf(df_new, coords = c("x","y"), crs=32632) %>% 
  mutate(dates = as.Date(dates, "%Y%m%d"))

ggplot(df_sf) +
  geom_col(aes(dates, precip)) +
  labs(x="", 
       y = "precipitation [mm]",
       title="Precipitation in Bolzano") +
  theme_light()
```


```{r getdata2, warning=F, message=F}
res = get_rainfall(data_path = path_ncdf,
                   spatial.obj = spatial.obj,
                   dts = dts,
                   seqq = seqq, 
                   days_back = days_back)

lapply(res, head)
```


```{r}
res_cumulative = rainfallR::get_cumulative_rainfall(res)
head(res_cumulative[[1]])
```


```{r}
max_date = max(res_cumulative[[2]]$dates)

ggplot(res_cumulative[[2]]) +
  geom_col(aes(dates, accumulated)) +
  theme_light() +
  labs(x = "Date",
       y = "Rainfall [mm]",
       title = paste0("Cumulative Rainfall in Bolzano prior to: ", max_date))
```



```{r leaflet, warning=F}
poly_path = "\\\\projectdata.eurac.edu/projects/Proslide/Landslides/Iffi_db_xxxx_to_2018/exportperEurac2020/Shapefiles/IFFI10_5.shp"

# read it with sf
spatial.obj = read_sf(poly_path)

# get only one landslide
spatial.obj = spatial.obj[1,]

# get the path to the nc file
path_to_nc = rainfallR::get_nc_paths(path_ncdf, day = as.Date("2016-01-12"), days_back = 1)[[1]]
# get the raster 
precip_raster_stack = raster::stack(path_to_nc)
# get the right date
precip_raster = precip_raster_stack[[12]]
# # crop to the shape
# crop = raster::crop(precip_raster, spatial.obj)
# precip_raster = raster::mask(crop, spatial.obj)

# transform the 
spatial.obj4326 = st_transform(spatial.obj, 4326)
# transform the raster
precip_raster = projectRaster(precip_raster, crs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")


# what have we got?
pal = colorNumeric(c("#0C2C84", "#41B6C4", "#FFFFCC"), values(precip_raster),
  na.color = "transparent")

leaflet() %>% 
  addTiles() %>% 
  setView(lng = st_coordinates(spatial.obj4326)[,1][[1]],
          lat = st_coordinates(spatial.obj4326)[,2][[1]],
          zoom=15) %>% 
  addPolygons(data = spatial.obj4326, group="shape") %>%
  addRasterImage(precip_raster, group = "precip", colors=pal) %>% 
  addLegend(pal=pal, values=values(precip_raster)) %>% 
  addLayersControl(overlayGroups = c("shape", "precip")) %>% 
  hideGroup("precip")
```

